import type { ComponentType } from 'react';
import { AnimSets, AnimDeMorgan, AnimSigmaClub, AnimCake, AnimSpotlights, AnimTree, AnimPerm, AnimComb, AnimStars, AnimGrid66, AnimWalkPath } from './visuals1';
import { AnimShrinkWorld, AnimPartitionFlow, AnimBayesFlow, AnimSpinners, AnimRVMachine, AnimStaircase, AnimGalton, AnimGeomTrials, AnimPoisTimeline, AnimJointGrid, AnimConvolve } from './visuals2';
import { AnimArea, AnimMemoryless, AnimJointTent, AnimBalance, AnimLotusLens, AnimDeviation, AnimCovarCloud, AnimLLNLine, AnimBulbs, AnimTailBound, AnimSlabs, AnimReturnWalk } from './visuals3';

/* Registry of animated visuals + the per-page programme:
   every content page of the PDF gets its own animations, captions and key formula. */

export const VIS: Record<string, ComponentType<any>> = {
  sets: AnimSets, demorgan: AnimDeMorgan, sigma: AnimSigmaClub, cake: AnimCake, spotlights: AnimSpotlights,
  tree: AnimTree, perm: AnimPerm, comb: AnimComb, stars: AnimStars, grid66: AnimGrid66, walkpath: AnimWalkPath,
  shrink: AnimShrinkWorld, partition: AnimPartitionFlow, bayesflow: AnimBayesFlow, spinners: AnimSpinners,
  rvmachine: AnimRVMachine, staircase: AnimStaircase, galton: AnimGalton, geomtrials: AnimGeomTrials,
  poisrain: AnimPoisTimeline, jointgrid: AnimJointGrid, convolve: AnimConvolve,
  area: AnimArea, memoryless: AnimMemoryless, tent: AnimJointTent, balance: AnimBalance, lotus: AnimLotusLens,
  deviation: AnimDeviation, covar: AnimCovarCloud, lln: AnimLLNLine, bulbs: AnimBulbs, tailbound: AnimTailBound,
  slabs: AnimSlabs, returnwalk: AnimReturnWalk,
};

export interface PageVisual {
  vis: keyof typeof VIS;
  props?: Record<string, unknown>;
  caption: string;          // one line — what this page's content IS, shown under the animation
  tex?: string;             // the page's key formula
  /** predict-before-reveal: commit to an answer before the animation shows the truth */
  predict?: { q: string; options: string[]; correct: number; why: string };
}

/** page → its animated demonstrations. Ranges expand below into PAGE_VISUALS. */
const RANGES: [from: number, to: number, visuals: PageVisual[]][] = [
  [7, 7, [{ vis: 'sets', caption: 'An experiment, its sample space Ω, and events as subsets — dice: E₁={2,4,6}, E₂={5,6}, E₃={1}.', tex: '\\Omega=\\{1,\\dots,6\\},\\quad E\\subseteq\\Omega',
    predict: { q: 'Roll one die. The event "even" is made of how many outcomes?', options: ['1', '3', '6'], correct: 1, why: 'an event is a SET of outcomes: {2,4,6} — three of the six worlds.' } }]],
  [8, 8, [{ vis: 'sets', caption: 'The four machines: union, intersection, difference, complement — and E = (E∩F) ∪ (E∩Fᶜ).', tex: 'E\\cup F,\\ E\\cap F,\\ E\\setminus F,\\ E^c',
    predict: { q: 'E∪F occurs when…', options: ['both E and F occur', 'at least one occurs'], correct: 1, why: 'union is the inclusive "or"; the "both" machine is intersection.' } }]],
  [9, 9, [{ vis: 'sets', caption: 'Figures 2–4: E∪F fires when at least one occurs, E∩F when both do, E\\F when only E does.', tex: 'E\\setminus F = E\\cap F^c',
    predict: { q: 'Which outcomes live in E\\F?', options: ['in E only', 'in F only', 'in both'], correct: 0, why: 'difference keeps E and evicts everything F touches: E∩Fᶜ.' } }]],
  [10, 10, [{ vis: 'sets', caption: 'Complement Eᶜ = everything outside E. Disjoint events cannot both happen: E∩F = ∅.', tex: 'E\\cap E^c=\\varnothing,\\quad E\\cup E^c=\\Omega',
    predict: { q: 'How many outcomes do E and Eᶜ share?', options: ['none, ever', 'sometimes a few'], correct: 0, why: 'a shared point would be in E and not in E at once — impossible.' } }]],
  [11, 12, [{ vis: 'demorgan', caption: 'De Morgan, proved by shading: outside-the-union equals outside-E AND outside-F.', tex: '(E\\cup F)^c=E^c\\cap F^c',
    predict: { q: 'The outside of E∪F equals…', options: ['Eᶜ ∪ Fᶜ', 'Eᶜ ∩ Fᶜ'], correct: 1, why: 'missing the union means missing BOTH — De Morgan flips ∪ into ∩.' } }]],
  [13, 14, [{ vis: 'sigma', caption: 'The σ-algebra club: ∅ joins free, members drag in complements, countable unions stay inside (Lemmas 1.1–1.2 use De Morgan + padding with ∅).', tex: 'E\\in\\mathcal F\\Rightarrow E^c\\in\\mathcal F,\\quad \\bigcup_i E_i\\in\\mathcal F',
    predict: { q: 'A σ-algebra contains E and F. Must it contain E∩F?', options: ['yes, always', 'not necessarily'], correct: 0, why: 'closed under complements and unions forces intersections too — De Morgan smuggles them in.' } }]],
  [15, 16, [{ vis: 'cake', caption: 'Kolmogorov: one cake of belief. Non-negative slices (A1), the whole cake is 1 (A2), disjoint slices add (A3) — and P(∅)=0 falls out.', tex: 'P\\Big(\\bigcup_i E_i\\Big)=\\sum_i P(E_i)',
    predict: { q: 'P(E) = 0.3. What is P(Eᶜ)?', options: ['0.3', '0.7', 'cannot say'], correct: 1, why: 'the whole cake is 1, so the complement takes whatever is left.' } }]],
  [17, 17, [{ vis: 'spotlights', caption: 'Complement, containment, partition rules — and why P(E∪F) needs the overlap removed.', tex: 'P(E\\cup F)=P(E)+P(F)-P(E\\cap F)',
    predict: { q: 'P(E)=0.5, P(F)=0.4. Is P(E∪F)=0.9 guaranteed?', options: ['yes', 'only if disjoint'], correct: 1, why: 'adding double-counts the overlap — subtract P(E∩F) unless it is empty.' } }]],
  [18, 19, [{ vis: 'spotlights', caption: 'Cluedo: disjoint murderers add; Mustard-or-Rope overlaps, so subtract the double-lit patch. Any non-negative pᵢ summing to 1 is a valid measure (Thm 1.3).', tex: 'P(M\\cup R)=\\tfrac{12}{27}+\\tfrac{9}{27}-\\tfrac{4}{27}',
    predict: { q: '"Mustard OR the rope": add the two probabilities, then…', options: ['done', 'subtract the overlap'], correct: 1, why: 'Mustard-with-the-rope was counted in both — remove the double-lit patch.' } }]],
  [20, 20, [{ vis: 'grid66', props: { mode: 'sum' }, caption: 'Classical probability = counting equally likely worlds. Three coins: 8 sequences, not 4 head-counts!', tex: 'P(E)=\\frac{|E|}{|\\Omega|}',
    predict: { q: 'Three coins: are {0, 1, 2, 3 heads} equally likely?', options: ['yes — four options', 'no'], correct: 1, why: 'SEQUENCES are equally likely: one head happens 3 ways, three heads only 1.' } }]],
  [21, 21, [{ vis: 'grid66', props: { mode: 'sum' }, caption: 'Two dice: 36 equally likely ordered pairs. Watch each total light its diagonal — 7 is richest.', tex: 'P(\\text{total}=6)=\\tfrac{5}{36}',
    predict: { q: 'Two dice: which total is most likely?', options: ['6', '7', '12'], correct: 1, why: '7 owns the longest diagonal — 6 of the 36 pairs.' } }]],
  [22, 23, [{ vis: 'tree', caption: 'The multiplication principle: stages multiply. Coin × dice × card = 2·6·52 = 624 worlds.', tex: '\\#=n_1\\times n_2\\times\\cdots\\times n_k',
    predict: { q: 'Toss a coin, roll a die, draw a card. How many combined outcomes?', options: ['60', '624', '112'], correct: 1, why: 'stages multiply: 2 · 6 · 52.' } }]],
  [24, 24, [{ vis: 'perm', caption: 'Ordered choices: with replacement nʳ (PIN codes), without n·(n−1)·… = n!/(n−r)!.', tex: 'n^r\\qquad \\frac{n!}{(n-r)!}',
    predict: { q: '4-digit PIN, digits MAY repeat. How many codes?', options: ['10·9·8·7', '10⁴'], correct: 1, why: 'with replacement every slot keeps all 10 choices.' } }]],
  [25, 25, [
    { vis: 'perm', caption: 'Five cards dealt in a row — order matters, no replacement: 52·51·50·49·48 worlds.',
      predict: { q: 'Committees of 3 from 10 people, vs ordered podiums of 3:', options: ['same count', 'fewer committees'], correct: 1, why: 'each committee shows up 3! = 6 times among podiums — divide the order away.' } },
    { vis: 'comb', caption: 'Forget the order and every group is counted r! times — divide it away: C(n,r).', tex: '\\binom{n}{r}=\\frac{n!}{r!(n-r)!}' },
  ]],
  [26, 26, [{ vis: 'comb', caption: 'Lottery: C(59,6) ≈ 45 million tickets. Full house: choose ranks, then suits — combinations glued by the multiplication principle.', tex: '\\binom{59}{6}=45{,}057{,}474',
    predict: { q: 'UK lottery: choose 6 numbers from 59. Roughly how many tickets?', options: ['45 thousand', '45 million'], correct: 1, why: 'C(59,6) = 45,057,474 — about 1 in 45 million.' } }]],
  [27, 27, [{ vis: 'stars', caption: 'The ice-cream machine: r scoops + (n−1) moves — choosing which presses are scoops counts unordered choices WITH repetition.', tex: '\\binom{n-1+r}{r}',
    predict: { q: '3 scoops from 4 flavours, repeats allowed. Does scoop order matter?', options: ['yes', 'no'], correct: 1, why: 'stars and bars counts UNORDERED choices with repetition — only the flavour counts matter.' } }]],
  [28, 28, [{ vis: 'perm', caption: 'ALGEBRA has repeated letters: 7! orderings, but swapping the two As changes nothing — divide by 2!.', tex: '\\frac{7!}{2!}=2520',
    predict: { q: 'Anagrams of ALGEBRA compared with 7! :', options: ['equal', 'half'], correct: 1, why: 'the two As are identical — swapping them changes nothing, so divide by 2!.' } }]],
  [29, 29, [{ vis: 'walkpath', caption: 'The urn and the first random-walk counting: ordered ±1 steps, 2ⁿ equally likely paths.', tex: '|\\Omega|=2^n',
    predict: { q: 'A fair ±1 walk takes 3 steps. Can it be back at 0?', options: ['yes', 'never'], correct: 1, why: 'returning needs equal ups and downs — an EVEN number of steps.' } }]],
  [30, 30, [{ vis: 'walkpath', caption: 'Back at 0 after n steps needs equal ups and downs: C(n, n/2)/2ⁿ — impossible for odd n.', tex: 'P(S_n=0)=\\binom{n}{n/2}2^{-n}',
    predict: { q: 'P(back at 0 after n steps) uses which count?', options: ['paths with n/2 ups', 'all monotone paths'], correct: 0, why: 'choose WHICH n/2 of the steps go up: C(n, n/2) of the 2ⁿ paths.' } }]],
  [31, 31, [{ vis: 'shrink', caption: 'Conditioning = shrinking the world: bin every world where F failed, renormalise by P(F). "At least two tails" vs "first two tails" give different worlds!', tex: 'P(E\\mid F)=\\frac{P(E\\cap F)}{P(F)}',
    predict: { q: 'Three tosses: P(TTT | at least two tails) vs P(TTT | FIRST two are tails):', options: ['equal', 'different'], correct: 1, why: '1/4 vs 1/2 — different information shrinks to different worlds.' } }]],
  [32, 32, [{ vis: 'shrink', caption: 'Chain rule: tell the story in order — two aces = (4/52)·(3/51). The fuses example chains three draws.', tex: 'P(E_1\\cap\\cdots\\cap E_n)=P(E_1)P(E_2|E_1)\\cdots',
    predict: { q: 'Two cards, no replacement. P(2nd ace | 1st was an ace) =', options: ['4/52', '3/51'], correct: 1, why: 'one ace and one card have left the deck.' } }]],
  [33, 33, [{ vis: 'partition', caption: 'A partition slices Ω into disjoint cases covering everything; F is computed case by case.', tex: 'P(F)=\\sum_i P(E_i)P(F\\mid E_i)',
    predict: { q: 'Cases E₁, E₂, E₃ split Ω. P(F) is…', options: ['the biggest P(F|Eᵢ)', 'a weighted average of them'], correct: 1, why: 'weights = case sizes P(Eᵢ): the law of total probability.' } }]],
  [34, 34, [
    { vis: 'partition', caption: 'The traders: 30/50/20% of deals × their profit rates — a weighted average gives P(>£1m) = 11/30.',
      predict: { q: 'Doctors know P(symptoms | disease). The patient wants…', options: ['exactly that', 'the reverse conditional'], correct: 1, why: 'P(disease | symptoms) — reversing the arrow is Bayes\' whole job.' } },
    { vis: 'bayesflow', caption: 'Bayes reverses the arrow: from P(F|E), which is easy to know, to P(E|F), which you want.', tex: 'P(E\\mid F)=\\frac{P(E)P(F\\mid E)}{P(F)}' },
  ]],
  [35, 35, [{ vis: 'bayesflow', caption: 'Of all routes to the observed loss, what fraction came through Buster? Numerator = his branch, denominator = every branch.', tex: 'P(B\\mid L)=\\tfrac12',
    predict: { q: 'Buster does 30% of deals but has the WORST loss rate. His share of the losses is…', options: ['30%', 'more than 30%'], correct: 1, why: 'share × rate drives the posterior: half of all losses trace to him.' } }]],
  [36, 36, [{ vis: 'spinners', caption: 'Independence = no gossip: P(E∩F) = P(E)P(F). Ace and hearts pass the test; disjoint events with positive probabilities fail it.', tex: 'P(E\\cap F)=P(E)P(F)',
    predict: { q: 'Draw ONE card. Are "ace" and "hearts" independent?', options: ['no — same card!', 'yes'], correct: 1, why: '1/52 = (1/13)(1/4): the numbers factorise; physical entanglement is irrelevant.' } }]],
  [37, 37, [{ vis: 'spinners', caption: 'Three events need all FOUR product checks. Two coins + "same side": every pair independent, the triple fails.', tex: 'P(E_1\\cap E_2\\cap E_3)\\ne P(E_1)P(E_2)P(E_3)',
    predict: { q: 'Every PAIR of E, F, G is independent. Are all three mutually independent?', options: ['yes', 'not necessarily'], correct: 1, why: 'two coins + "same side": pairs pass, the triple product fails.' } }]],
  [38, 38, [{ vis: 'spinners', caption: 'Three missiles: P(at least one hit) = 1 − P(all miss) = 1 − 0.3·0.2·0.1. Independence survives complements.', tex: '1-\\prod_i(1-p_i)',
    predict: { q: 'Hit chances 0.7, 0.8, 0.9. Fastest route to P(at least one hit)?', options: ['add them up', '1 − P(all miss)'], correct: 1, why: 'complement + independence: 1 − 0.3·0.2·0.1 = 0.994. Adding gives 2.4 — nonsense.' } }]],
  [39, 40, [{ vis: 'walkpath', caption: 'Recurrence teaser + the prosecutor\'s fallacy: P(evidence|innocent) is NOT P(innocent|evidence).', tex: 'P(E\\mid G^c)\\ne P(G^c\\mid E)',
    predict: { q: '"1 in 73 million chance if innocent" therefore "1 in 73 million she is innocent"?', options: ['sound reasoning', 'a fallacy'], correct: 1, why: 'that transposes P(E|innocent) into P(innocent|E) — the prosecutor\'s fallacy that helped convict Sally Clark.' } }]],
  [41, 41, [
    { vis: 'bayesflow', caption: 'Sally Clark, done right: with real priors the posterior is under ½ — not 1 in 73 million.',
      predict: { q: 'A random variable is…', options: ['a number that is random', 'a fixed function of the outcome'], correct: 1, why: 'X: Ω → ℝ is a fixed machine; only the outcome ω fed into it is random.' } },
    { vis: 'rvmachine', caption: 'A random variable is a fixed machine turning random outcomes into numbers: X: Ω → ℝ.', tex: 'X:\\Omega\\to S\\subseteq\\mathbb R' },
  ]],
  [42, 42, [{ vis: 'rvmachine', caption: 'Figure 14, animated: HHT flows through X and lands at 2. Many machines can read one experiment.', tex: '\\{X=x\\}=\\{\\omega: X(\\omega)=x\\}',
    predict: { q: 'Three tosses, X = number of heads. P(X = 1) =', options: ['1/4', '3/8'], correct: 1, why: 'three of the eight sequences (HTT, THT, TTH) land at 1.' } }]],
  [43, 43, [{ vis: 'rvmachine', caption: 'The pmf: probability sand per value — bars {1/8, 3/8, 3/8, 1/8} summing to exactly 1.', tex: 'f_X(x)=P(X=x),\\quad \\textstyle\\sum f_X=1',
    predict: { q: 'Sum every pmf value. You must get…', options: ['at most 1', 'exactly 1'], correct: 1, why: 'the sand accounts for every possible outcome — nothing missing, nothing extra.' } }]],
  [44, 45, [{ vis: 'staircase', caption: 'The cdf collects sand left→right: a staircase climbing 0 → 1, flat between values, jumping by each mass.', tex: 'F_X(x)=P(X\\le x)',
    predict: { q: 'Between two support points the cdf…', options: ['climbs slowly', 'stays perfectly flat'], correct: 1, why: 'nothing new accumulates until the next value — flat, then jump.' } }]],
  [46, 46, [{ vis: 'staircase', caption: 'Read the pmf back from the cdf: each jump height IS P(X = x). Bernoulli: one step of size p.', tex: 'P(a<X\\le b)=F(b)-F(a)',
    predict: { q: 'The jump height of the cdf at x equals…', options: ['P(X < x)', 'P(X = x)'], correct: 1, why: 'the staircase stores the pmf in its jumps.' } }]],
  [47, 48, [{ vis: 'galton', caption: 'n independent left/right choices pile into the binomial: C(n,x) routes × pˣ(1−p)ⁿ⁻ˣ each.', tex: 'P(X=x)=\\binom{n}{x}p^x(1-p)^{n-x}',
    predict: { q: 'Bin(100, 0.5): where does the probability pile up?', options: ['near 50', 'spread evenly'], correct: 0, why: 'the mountain centres at np = 50 — middle counts have the most routes.' } }]],
  [49, 50, [{ vis: 'geomtrials', caption: 'Geometric: fail, fail, …, WIN. Support starts at 1 in this course; each bar is (1−p)× the previous.', tex: 'P(X=k)=(1-p)^{k-1}p',
    predict: { q: 'Each geometric bar shrinks by a factor of…', options: ['p', '1 − p'], correct: 1, why: 'waiting one more trial costs exactly one more failure: ×(1−p).' } }]],
  [51, 51, [{ vis: 'geomtrials', caption: '"Still waiting after n" = n straight failures: P(X>n) = (1−p)ⁿ — the cdf with no summing.', tex: 'P(X>n)=(1-p)^n',
    predict: { q: 'For Geom(p), P(X > n) =', options: ['(1−p)ⁿ', '1 − pⁿ'], correct: 0, why: '"still waiting" simply means n straight failures.' } }]],
  [52, 54, [{ vis: 'poisrain', caption: 'Events at rate λ: rescale to your window (Freddie: 1.2/min × 20min = 24). Mean = variance = λ.', tex: 'P(X=x)=\\frac{\\lambda^x}{x!}e^{-\\lambda}',
    predict: { q: 'Sneezes at 1.2/minute. For a 20-minute window, λ =', options: ['1.2', '24'], correct: 1, why: 'rescale the rate to the window: 1.2 × 20. Forgetting this is THE Poisson error.' } }]],
  [55, 55, [
    { vis: 'poisrain', caption: 'Westminster accidents fit Pois(4.18); large-n small-p binomials collapse to Poisson with λ = np.',
      predict: { q: 'Merge two independent Poisson streams. The result is…', options: ['something new', 'Poisson with rates added'], correct: 1, why: 'Pois(λ) + Pois(μ) = Pois(λ+μ) — rates simply add.' } },
    { vis: 'jointgrid', caption: 'Two rvs on one experiment: the joint table holds everything.', tex: 'f_{X,Y}(x,y)=P(X=x,Y=y)' },
  ]],
  [56, 57, [{ vis: 'jointgrid', caption: 'Marginals live in the margins: sum a row to forget Y, a column to forget X — total probability in disguise.', tex: 'f_X(x)=\\sum_y f_{X,Y}(x,y)',
    predict: { q: 'Summing one ROW of a joint table gives…', options: ['a marginal', 'a conditional'], correct: 0, why: 'forgetting Y = law of total probability = the marginal of X.' } }]],
  [58, 60, [{ vis: 'spinners', caption: 'Independent rvs: EVERY cell equals row × column. One failing cell — especially a zero — breaks it (X and X+Y fail instantly).', tex: 'f_{X,Y}(x,y)=f_X(x)f_Y(y)',
    predict: { q: 'X = first die, Z = X + Y. Independent?', options: ['yes', 'no'], correct: 1, why: 'P(X=1, Z=12) = 0 while neither factor is 0 — one dead cell kills independence.' } }]],
  [61, 62, [{ vis: 'convolve', caption: 'Sum of independent rvs: pair every split x and k−x. Poisson + Poisson merges rates: Pois(λ+μ).', tex: 'P(X+Y=k)=\\sum_x P(X=x)P(Y=k-x)',
    predict: { q: 'P(X+Y = 5): which splits contribute?', options: ['just x=5, y=0', 'every x paired with 5−x'], correct: 1, why: 'convolution sums over ALL ways of sharing the total.' } }]],
  [63, 63, [{ vis: 'convolve', caption: 'Bin(n,p) + Bin(m,p) pools the trials — computing it twice proves Vandermonde\'s identity.', tex: '\\binom{n+m}{k}=\\sum_x\\binom{n}{x}\\binom{m}{k-x}',
    predict: { q: 'Bin(n,p) + Bin(m,p), independent, same p. The sum is…', options: ['Bin(n+m, p)', 'Bin(n+m, 2p)'], correct: 0, why: 'pool the trials — the success chance per trial never changed.' } }]],
  [64, 64, [{ vis: 'area', props: { dist: 'unif' }, caption: 'Uniform: a flat brick of probability. Interval probability = length/(b−a), position irrelevant.', tex: 'F_X(x)=\\frac{x-a}{b-a}',
    predict: { q: 'X ~ Unif(2,6): P(X ∈ (3,4]) vs P(X ∈ (5,6])', options: ['equal', 'different'], correct: 0, why: 'only LENGTH matters for a uniform — both intervals have length 1, so both are 1/4.' } }]],
  [65, 65, [
    { vis: 'area', props: { dist: 'unif' }, caption: 'Unif(0,1) is the mother of simulation: stretch it (×360) and it stays uniform.',
      predict: { q: 'Events arrive as a Poisson stream. The wait for the FIRST one is…', options: ['Exponential', 'Uniform'], correct: 0, why: 'P(T > t) = P(no arrivals by t) = e^(−μt) — the exponential cdf appears.' } },
    { vis: 'area', props: { dist: 'exp' }, caption: 'Exponential: the waiting-time curve. First arrival of a Pois(μt) stream is Exp(μ).', tex: 'F(x)=1-e^{-\\lambda x}' },
  ]],
  [66, 66, [{ vis: 'memoryless', caption: 'Memorylessness: given you have waited x, the remaining wait is a brand-new Exp(λ). The e^{−λx} factors cancel.', tex: 'P(X\\le x+y\\mid X>x)=P(X\\le y)',
    predict: { q: 'You have already waited 5 minutes for an Exp(λ) event. The REMAINING wait is…', options: ['shorter on average', 'a brand-new Exp(λ)'], correct: 1, why: 'memorylessness — the clock restarts; nothing is ever "due".' } }]],
  [67, 69, [{ vis: 'area', props: { dist: 'norm' }, caption: 'The Normal: μ slides the bell, σ² fattens it, the area is always 1. Its cdf has no formula — Φ is computed numerically.', tex: 'f(x)=\\tfrac{1}{\\sqrt{2\\pi\\sigma^2}}e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}',
    predict: { q: 'Increase σ². The bell curve…', options: ['slides right', 'gets wider and flatter'], correct: 1, why: 'μ slides it, σ² spreads it — the area stays exactly 1.' } }]],
  [70, 71, [{ vis: 'area', props: { dist: 'exp' }, caption: 'Probability IS area: P(1<X≤2) = e⁻¹ − e⁻² ≈ 0.2325 for Exp(1). Densities may exceed 1; areas cannot.', tex: 'P(a<X\\le b)=\\int_a^b f(u)\\,du',
    predict: { q: 'Can a pdf take the value 2?', options: ['never — probabilities ≤ 1', 'yes'], correct: 1, why: 'Unif(0, 1/2) has f = 2 everywhere. Only AREAS are probabilities, not heights.' } }]],
  [72, 75, [{ vis: 'tent', caption: 'Joint density = a tent of probability. Rectangle probability = the volume above it; squash one axis flat to get a marginal.', tex: 'f_X(x)=\\int f_{X,Y}(x,y)\\,dy',
    predict: { q: 'To get the marginal pdf of X from a joint pdf…', options: ['integrate y out', 'differentiate in x'], correct: 0, why: 'squash the tent flat onto the x-axis — the continuous "sum the row".' } }]],
  [76, 78, [{ vis: 'tent', caption: 'Independence = the tent weaves from two separate ridgelines: f(x,y) = g(x)h(y). Triangle-shaped supports can never separate.', tex: 'f_{X,Y}=f_X\\,f_Y',
    predict: { q: 'f(x,y) = g(x)h(y) for SOME non-negative g, h. Independent?', options: ['must find the marginals first', 'yes, already proven'], correct: 1, why: 'any separation suffices (Thm 5.5) — the marginals are just rescalings of g and h.' } }]],
  [79, 79, [{ vis: 'balance', caption: 'Expectation is the balance point of the masses — a fair dice balances at 3.5, a value it cannot roll.', tex: 'E[X]=\\sum x\\,P(X=x)',
    predict: { q: 'A fair die "expects"…', options: ['a value it can roll', '3.5'], correct: 1, why: 'the balance point of the six masses — attainability not required.' } }]],
  [80, 80, [{ vis: 'balance', caption: 'Continuous version: the jam shelf balances at ∫x f(x)dx. Exp(λ) balances at 1/λ — higher rate, shorter wait.', tex: 'E[X]=\\int x f(x)\\,dx',
    predict: { q: 'Buses arrive at rate 10/hour (Exp). Mean wait =', options: ['10 hours', '1/10 hour'], correct: 1, why: 'mean = 1/λ — rate and average wait are reciprocals.' } }]],
  [81, 81, [{ vis: 'lotus', caption: 'LOTUS: push values through g, keep the weights. E[X²] is the average of squares — never the square of the average.', tex: 'E[g(X)]=\\sum g(x)P(X=x)',
    predict: { q: 'Fair die: E[X²] vs (E[X])²', options: ['equal', 'different'], correct: 1, why: '91/6 ≈ 15.2 vs 12.25 — the "law of the incompetent statistician" strikes.' } }]],
  [82, 84, [{ vis: 'balance', caption: 'Linearity: E[aX+bY] = aE[X]+bE[Y] with NO independence needed. E[Bin] = np in one line via Bernoulli bricks. Products DO need independence.', tex: 'E[aX+bY]=aE[X]+bE[Y]',
    predict: { q: 'E[X+Y] = E[X] + E[Y] requires independence.', options: ['true', 'false'], correct: 1, why: 'linearity NEVER needs independence — only products of expectations do.' } }]],
  [85, 87, [{ vis: 'deviation', caption: 'Variance: square the deviations, then average. Shifts are free, scales enter squared: Var(aX+b) = a²Var(X).', tex: '\\mathrm{Var}(X)=E[X^2]-(E[X])^2',
    predict: { q: 'Var(2X + 5) =', options: ['2·Var(X) + 5', '4·Var(X)'], correct: 1, why: 'shifts are free, scales enter SQUARED — variance is not linear.' } }]],
  [88, 89, [{ vis: 'covar', caption: 'Covariance: do deviations agree (green) or fight (red)? Correlation squeezes it into [−1, 1].', tex: '\\mathrm{Cov}(X,Y)=E[XY]-E[X]E[Y]',
    predict: { q: 'Independent ⟹ Cov = 0. Does Cov = 0 ⟹ independent?', options: ['yes, equivalent', 'no'], correct: 1, why: 'covariance only detects LINEAR association — dependent-but-uncorrelated examples exist.' } }]],
  [90, 91, [{ vis: 'deviation', caption: 'Var(X±Y) = Var + Var ± 2Cov — subtracting noise still ADDS its variance; independence kills the cross-term. Bin variance: np(1−p).', tex: '\\mathrm{Var}(X\\pm Y)=\\mathrm{Var}X+\\mathrm{Var}Y\\pm 2\\,\\mathrm{Cov}',
    predict: { q: 'X, Y independent. Var(X − Y) =', options: ['Var(X) − Var(Y)', 'Var(X) + Var(Y)'], correct: 1, why: 'subtracting a noisy thing still ADDS its noise — variances add for any ± combination.' } }]],
  [92, 93, [{ vis: 'lln', caption: 'The Law of Large Numbers live: averaging divides the wobble by √n — luck evens out, estimates converge.', tex: '\\mathrm{Var}(\\bar X_n)=\\sigma^2/n\\to 0',
    predict: { q: 'Quadruple your sample size. Var(X̄) is divided by…', options: ['4', '2'], correct: 0, why: 'Var(X̄ₙ) = σ²/n — four times the data, a quarter of the variance (sd halves).' } }]],
  [94, 94, [
    { vis: 'bulbs', caption: 'Indicators: a bulb per event, E[bulb] = P(A). Count anything by summing bulbs — dependence irrelevant.', tex: 'E[\\mathbb 1_A]=P(A)',
      predict: { q: 'Markov\'s bound uses ONLY the mean. It is…', options: ['razor sharp', 'loose but universal'], correct: 1, why: 'it can be off by factors of millions — its power is needing almost no information.' } },
    { vis: 'tailbound', caption: 'Markov: the mean is a leash on the tail — P(X ≥ x) ≤ E[X]/x for non-negative X.', tex: 'P(X\\ge x)\\le E[X]/x' },
  ]],
  [95, 95, [{ vis: 'tailbound', caption: 'Chebyshev = Markov on |X−E[X]|²: variance caps both tails — and proves the LLN in two lines.', tex: 'P(|X-E[X]|\\ge x)\\le \\mathrm{Var}(X)/x^2',
    predict: { q: 'Chebyshev is Markov applied to…', options: ['X itself', '(X − E[X])²'], correct: 1, why: 'squaring the deviation turns mean-control into spread-control — and proves the LLN.' } }]],
  [96, 97, [{ vis: 'slabs', caption: 'The tail-sum formula: stack "at least this tall" slabs and they pile into E[X] — Geom and Exp means in one line.', tex: 'E[X]=\\int_0^\\infty P(X\\ge x)\\,dx',
    predict: { q: 'For X ≥ 0, E[X] equals the area under…', options: ['the pdf', 'the survival curve P(X ≥ x)'], correct: 1, why: 'stack the "at least this tall" slabs — they pile up into the mean.' } }]],
  [98, 98, [{ vis: 'returnwalk', caption: 'The finale: the walk returns to 0 with probability 1, yet E[return time] = ∞. Certainty and patience differ.', tex: 'P(T<\\infty)=1,\\quad E[T]=\\infty',
    predict: { q: 'The walk returns to 0 with probability 1. So E[return time] is…', options: ['finite', 'possibly infinite'], correct: 1, why: 'it IS infinite: 1/√n tails sum to ∞ — certainty says nothing about patience.' } }]],
];

export const PAGE_VISUALS: Record<number, PageVisual[]> = {};
for (const [a, b, vs] of RANGES) for (let p = a; p <= b; p++) PAGE_VISUALS[p] = vs;
